/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import java.awt.Color;
import java.awt.Graphics;
import main.Main;

/**
 *
 * @author ACER
 */
public class highWay extends manualFix{

    /**
     * Creates new form highWay
     */
    public highWay(int Starty,int LenghtY) {
        super.setLenghtY(LenghtY);
        super.setPoints(0, Starty);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void draw(Graphics g) {
        super.setLenghtX(Main.WidthFrame);
        
        g.setColor(Color.gray);
        g.fillRect(super.getXPoints(), super.getYPoints(), super.getLenghtX(), super.getLenghtY());
        
        g.setColor(Color.white);
        for(int i=0;i<super.getLenghtX();i+=super.getLenghtX()/10)
        {
            g.fillRect(super.getXPoints()+i, super.getYPoints(), super.getLenghtX()/20, super.getLenghtY()/15);
        }
        //g.setColor(Color.yellow);
        //g.fillRect(super.getXPoints()-super.getLenghtX()/35, super.getYPoints()+(35*super.getLenghtY()/36), super.getLenghtX(), super.getLenghtY()/50);
    
        //g.fillRect(super.getXPoints()-super.getLenghtX()/35, super.getYPoints()+(super.getLenghtY()/80), super.getLenghtX(), super.getLenghtY()/50);    
    }
}
